### ISSUE TITLE
辞書を扱いやすくする

### ISSUE THREAD

**Issue by elipmoc** [MineMonsterLabo/marine-lang#149]
## Dicitonary<string,object>の生成

```
let t = ${}

let tt = ${
    a : 888,
    b : "aaa"
    c: : {|x| x+1}
}
```

---

## IDicitonaryの要素追加

```
t.acac = 888

t.set_value("aabb",1122)
```

---

## IDicitonaryの要素削除

```
t.delete("a")
```

対応するキーが無くても、例外は投げない。
対応するキーがあった場合、trueを返す。

---

## IDicitonaryへアクセス

```
//acacが無い場合、例外
let b = t.acac
let c = t.get_value("acac")

// kkkが無い場合、123が返る
let d = t.get_value_or("kkk",123)

```
---

## 制約
`table.element`のアクセス方法では、
キー名にはスネークケースしか付けれない。
キー名を大文字で扱いたいときは、
`set_value,get_value`などを使用する。

## C#側の扱い

`IDicitonary`インターフェイスのインスタンスとして利用可能。

**Comment by hiroki19990625** [comment]
良さそうです!
