### ISSUE TITLE
グローバルに対する明示的なアクセス

### ISSUE THREAD

**Issue by hiroki19990625** [MineMonsterLabo/marine-lang#184]
globalネームスペースでアクセス

**Comment by elipmoc** [comment]
## global名前空間に配置されるものについて
- GlobalFuncRegisterで登録した関数。
- GlobalVariableRegisterで登録した変数。
- グローバル名前空間上で定義したMarineLang関数

## 明示的なglobal名前空間へのアクセス

`global::hoge()`

これを導入することで、ローカルと名前被りした際にも、グローバルを呼び出せる
