### ISSUE TITLE
&& || 演算子の評価順序が逆転している

### ISSUE THREAD

**Issue by hiroki19990625** [MineMonsterLabo/marine-lang#228]
![image](https://user-images.githubusercontent.com/18022692/194367311-24ae1418-0724-4d6f-90c9-d0f2b83cd2ec.png)
本来は緑色の方向に評価されるへきなのですが、  
現状、MarineLangでは赤色の方向に評価されてしまう。
(順序が逆転している)

**Comment by elipmoc** [comment]
草

**Comment by elipmoc** [comment]
問題なかったのでclose
